### PR TITLE
fix: Some grammatical corrections

### PR DESCRIPTION
**Pull request by jonas-martinez**
Done some grammatical corrections on the website.

### CODE REVIEW

**Review by taorepoara — APPROVED** [review]

**Comment by taorepoara** [comment]
Your commit message was not correct so the app has not been released.

We can wait for the next evolution to include your changes or push an empty commit to the main branch to force the release

**Comment by jonas-martinez** [comment]
My bad, I didn't see that it was a "docs" commit. I'm going to push an empty commit.

**Comment by taorepoara** [comment]
NP.
Did you squash for the merge ? I think that squashing would have override your commit, but not sure since there is only one commit :thinking:

**Comment by jonas-martinez** [comment]
That's what I was wondering. Every repo on lenra-io is set to "squash on merge", maybe not this one 😆

**Pull request merged**
